### ISSUE TITLE
some-radio appending duplicate error to each radio

### ISSUE THREAD

**Issue by essmahr** [casperin/nod#115]
If `some-radio` is meant to target a group of radio inputs, should it not only surface a single error message if the condition isn't met?

When I use this validator along with the selector shared by each radio input in my group:

```
{
  selector: '[name="radio_group"]',
  validate: 'some-radio',
  errorMessage: 'error message.'
}
```
I get the following:

![image](https://cloud.githubusercontent.com/assets/5510974/10058065/48a728d8-61f8-11e5-8eb4-a4b30cedd952.png)

In most cases I imagine the desired functionality in this case would be a single message at the bottom. I'm thinking there's a way with the `parent` option in setMessageOptions but there's nothing in the documentation to suggest this can be done on a validator-by-validator level. Thoughts?

**Comment by casperin** [comment]
Hi @essmahr, sorry about my ridiculously late response here.

I haven't looked at this project for a long time, but I remember radio buttons being very difficult to get right (I got them very wrong in v1.x). If I recall correctly, I think I saw this solution as the programatically most sensible way to do things, and then yes, as you point out, you could do magic with the `parent` option. I don't remember exactly how it goes to be honest.

Did you work it out? If so, could you let me know, so I can update the documentation? Even, if you feel like it, feel free to do a pull request on the README. I know it's not considered code, but imo it's the most important file in this whole project. Just saying.

**Comment by casperin** [comment]
Okay, I got it now. It's not about the `parent`, but about using `setMessageOptions`. Like this:

```js
myNod.setMessageOptions({
  selector: '.radio',
  errorSpan: '.error-message-here'
});
```

And [here is a codepen](http://codepen.io/anon/pen/GojOja?editors=101) with the full code. I will add something similar to the `/examples` and to the documentation.

**Comment by tigermarques** [comment]
Hi all,

Regarding this issue, I've been having trouble performing validations on radio buttons if I have multiple radio groups. If I have only one group, like @essmahr example, the setMessageOptions seems to work like a charm. However, if I add another radio button group, the error message span only shows for the first group. I set forked the codepen and tweeked it a little
http://codepen.io/anon/pen/XdmPQo?editors=101

@casperin is there a way to add the validation so that it works with multiple radio groups?

Thanks a lot!
